### ISSUE TITLE
Align two Visium datas

### ISSUE THREAD

**Issue by Lixinyoung** [JEFworks-Lab/STalign#21]
Is it possible to align two Visium-like datas? Like align a Visium to a DBiT data, or just align a Visium two another Visium data.

**Comment by estellad** [comment]
Hi there, 

I have tried aligning Visium coordinates to Xenium HE (the other direction of their tutorial Xenium coordinates to Visium HE), so it is possible. To rasterize Visium, their function `STalign.rasterize` has an option `'g'` that takes the RNA count of the cell. :)

Hope that helps :D

Sincerely,
Estella

**Comment by Lixinyoung** [comment]
Thanks, @estellad:
 
I didn't realize that there is a `'g'` option in the function `STalign.rasterize`. This solve my question perfectly!

Yours sincerely,
Lixinyoung

**Comment by JEFworks** [comment]
Thanks @estellad! Appreciate it.
