### ISSUE TITLE
[Just a question] Point vs. Curve annotator

### ISSUE THREAD

**Issue by estellad** [JEFworks-Lab/STalign#22]
Hi there,

I found two tutorials on the same datasets, but one uses point and the other uses curve annotator. Is there a preference for one over another and in what situations? For example, if it's a simple linear transformation, go with a point annotator, but if it's mostly non-linear twisting, use a curve annotator? 

https://jef.works/STalign/notebooks/merfish-visium-alignment-with-curve-annotator.html
https://jef.works/STalign/notebooks/merfish-visium-alignment-with-point-annotator.html 

Thank you for your help!

Sincerely,
Estella

**Comment by kpclifton** [comment]
Hi Estella,

Thanks for your question. The point_annotator is the correct version to use. The point_annotator is an updated version of the curve_annotator which some more user friendly features and a more appropriate name.

Best,
Kalen
