### ISSUE TITLE
using transcript coordinates as input

### ISSUE THREAD

**Issue by pr4deepr** [JEFworks-Lab/STalign#23]
Hi
  Thanks for the great software and documentation. 
Instead of cell coordinates, I've been using the transcript coordinates with STalign. 
I have to downsample the data a fair bit, but it seems to work well. 

Is this approach reasonable?
What do I need to be careful of?

Cheers
Pradeep

**Comment by kpclifton** [comment]
Hi Pradeep,

Thanks for your use of STalign. I think the approach of using transcript coordinates is reasonable.  I think as long as the two datasets that you are aligning broadly share the same spatial features it shouldn't matter much if the features are a function of cell density or transcript density or something else. One thing that you could be careful of is choosing a rasterization resolution that makes sense for how dense your transcript coordinates are. Feel free to let me know if there are any specific challenges that you encounter.

Best,
Kalen

**Comment by pr4deepr** [comment]
Hi Kalen
  I really appreciate the answer. Thanks a lot.

The data sets do share the same spatial features but I wasn't sure if I was overlooking anything.

Good point about the rasterization resolution. Would using large resolution values lead to faster rasterization? 
As there are a lot of transcripts, compared to cells, I usually have to take a subset of the transcript data to perform rasterization.

Cheers
Pradeep

**Comment by kpclifton** [comment]
Hi Pradeep,

The current implementation of rasterization scales linearly with the number of points inputted not the number of pixels outputted so unfortunately changing the resolution would not lead to faster rasterization. However, the downstream functions scale with respect to the number of pixels so larger resolutions would likely decrease time for those processes.

Best,
Kalen

**Comment by kpclifton** [comment]
Thanks for your questions. This implementation of rasterization has not been parallelized or optimized for speed.

**Comment by JEFworks** [comment]
Dear Pradeep,

You're welcome to modify the `rasterize` function (https://github.com/JEFworks-Lab/STalign/blob/main/STalign/STalign.py#L61) to parallelize. There is a for loop (L152) that can definitely be done in parallel. We've done some optimization previously using small windows, which has generally made it fast enough for our use cases, but this can always be improved. If you develop a solution, you're welcome to contribute it via a pull request and I'd be happy to review it. 

Best,
Jean

**Comment by pr4deepr** [comment]
Thanks @kpclifton and @JEFworks . Really appreciate the responses. 
I'll look into if I can help with optimizing it. Will create a PR when I do.
Also, congrats on the publication too. Its a really software tool.
