### ISSUE TITLE
[STalign] code for fig 3 c,d

### ISSUE THREAD

**Issue by jpark27** [JEFworks-Lab/STalign#24]
Dear @kpclifton & @JEFworks,

Hi, all! First of all, thank you so much for sharing great tool & in-depth tutorials for ST community.

I managed to successfully install STalign and benchmark `[merfish-visium-alignment.ipynb]` but I couldn't find any code snipet in git/tutorial link/zenodo/paper supplementary when I try to replicate Figure 3 c&d.

![image](https://github.com/JEFworks-Lab/STalign/assets/59645310/8454be2b-8a49-4cfa-a963-0d451cdd31d3)

If it's ok, can you kindly share how authors did such correspondence evaludation inbtw merfish and visium data so users can reproduce?

Any commnets would be appreciated,
Jun

**Comment by kpclifton** [comment]
Hi Jun,

Thanks for using STalign! Glad to hear you were able to successfully use the `[merfish-visium-alignment.ipynb]` tutorial. 

For replicating figure 3 c&d, we describe the analysis in the Methods section of the paper under ["Evaluation alignment across technologies: Expression based performance."](https://www.nature.com/articles/s41467-023-43915-7#Sec9) To do expression correspondence evaluation with the aligned cell positions you have generated, you can access the MERFISH and Visium gene count data from https://info.vizgen.com/mouse-brain-map and https://www.10xgenomics.com/resources/datasets/adult-mouse-brain-ffpe-1-standard-1-3-0 respectively as mentioned in the paper.  

Alternatively, you can use the cell positions after alignment that are available in the [Zenodo repository](https://zenodo.org/records/8384019) as `STalign_S2R3_to_Visium.csv.gz`. 

We did not provide code as this downstream analysis is outside of the scope of the alignment tool. If you have questions about the written description, I'd be happy to answer them.

Best,
Kalen
