### ISSUE TITLE
Aligning pathologist annotation and spatial transcriptomics

### ISSUE THREAD

**Issue by pakiessling** [JEFworks-Lab/STalign#28]
Hi there,

thank you for the package – impressive work!

My use case is the following:

I have spatial transcriptomic measurements and matching HE stains.
Our pathologists like to annotate tissues by drawing shapes on the .tif in powerpoint...

My goal is to transfer the the annotation to the single cell resolution spatial transcriptomic data.

How do I best accomplish that?
a) Do I try and align the annotated HE stain or
b) Align the unaltered HE and transfer the transformation to the annotated picture somehow?

Thank you!

**Comment by kpclifton** [comment]
Hi,

Thanks for your interest in using STalign!

I think with STalign you could align the single cell spatial transcriptomics data to either the unaltered or annotated HE (depending on how much the annotations disrupt the features in the HE). We have a few tutorials demonstrating aligning single cells and HE stained images (https://jef.works/STalign/notebooks/xenium-heimage-alignment.html and https://jef.works/STalign/notebooks/merfish-visium-alignment-with-point-annotator.html).

However, even if you are able to align with the annotated HE, I think it will be challenging to transfer the annotations if they are drawn onto the image without coordinates to indicate where the lines are drawn in the image.

Perhaps you can use another tool such as QuPath (https://github.com/qupath/qupath) or GiottoSuite (https://drieslab.github.io/Giotto_website/articles/interactive_selection.html) to trace the pathologist’s annotations to get polygons with coordinates that describe where the polygons are relative to the HE.  Then once you use STalign to align the single cells to the HE, you can select the cells that are within the polygon coordinates. 

Best,
Kalen

**Comment by pakiessling** [comment]
Thanks that's super helpful!

I will try that
