### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by JLiLab** [JEFworks-Lab/STalign#3]
pip install "git+https://github.com/JEFworks-Lab/STalign.git" met with the following error:
ERROR: git+https://github.com/JEFworks-Lab/STalign.git does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

**Comment by JLiLab** [comment]
This may be a problem specific to OSX or Apple M1 machine. The installation went well on windows.

**Comment by mmganant** [comment]
Thanks for bringing this to our attention! I believe the package should run on Apple M1 with our latest push to the repository. Please let us know.

**Comment by JLiLab** [comment]
It works. Thank you for the incredibly prompt response!
