### ISSUE TITLE
Parameter for better alignment

### ISSUE THREAD

**Issue by jonas2612** [JEFworks-Lab/STalign#36]
Hello,

thank you for this method! It really helps a lot.

I'm currently working with mouse brain slices which I'm partially aligning with the Allen Atlas. So far the alignment works well, but I'm still requiring a more precise mapping. 
![overlay_dx_10_blur_1_slce_139_deg_79 0_pnts_12_nt_4_diff_10](https://github.com/user-attachments/assets/68467d8f-6e2f-4d42-9692-56e1e8703c46)

I have done a parameter search and adjusted nt to 4 and 10 and diff between 5 and 30 in the transformation, use niter=800 and currently use 12 points.

Can you recommend maybe other parameters that would increase the accuracy of the mapping or better ranges of the current parameters?

Any guidance would be greatly appreciated!

Best,
Jonas

**Comment by mmganant** [comment]
Hi Jonas, these parameters seem reasonable. I would also try increasing the epV parameter and/or increasing the sigmaM parameters to allow for more flexible velocity fields and increased distortion in the target image, potentially allowing for better alignment in your case. You could also decrease 'a', which leads to increased local distortions. Let me know if these suggestions are helpful.
Best, Manjari

**Comment by jonas2612** [comment]
Hi Manjari,
thank you for the suggestions. I tried them and the results improved.

During working with STalign I wrote code that makes it easier to rotate the reference points with the picture of the atlas, which is quite useful when trying to find the right angle for the mapping i.e. in a grid search. Basically, you can fix the reference points at any angle you choose and the function turns the reference points with the atlas picture. It expects points annotated as (x,y). They are switched later to the required format later.

```
def ref_point_rotation(theta_deg, points_atlas, slice, theta_deg_base, extentA, A):
""" theta_deg: wanted rotation of atlas
      theta_deg_base: annotation rotation
    """
    atl_rot_base = rotate(A[slice], angle=theta_deg_base)
    atl_rot = rotate(A[slice], angle=theta_deg)
    #step 1)
    # transfer of points to original scale
    org_offset_x = min(extentA[0], extentA[1])
    org_offset_y = min(extentA[2], extentA[3])
    org_scaling_x = (max(extentA[0], extentA[1])-org_offset_x)/atl_rot_base.shape[1]
    org_scaling_y = (max(extentA[2], extentA[3])-org_offset_y)/atl_rot_base.shape[0]

    points_atlas_base_x = (points_atlas[:,0]-org_offset_x)/org_scaling_x
    points_atlas_base_y = (points_atlas[:,1]-org_offset_y)/org_scaling_y
    
    #step 2)
    # rotate coordinates
    #step 2.1)
    # put rotation point in the middle
    points_atlas_base_middle = np.array([points_atlas_base_x-atl_rot_base.shape[1]/2,
                                        points_atlas_base_y-atl_rot_base.shape[0]/2])
        
    #step 2.2)
    # rotate matrix
    rotation_matrix = np.array([[np.cos((np.pi/180)*(theta_deg_base-theta_deg)),-np.sin((np.pi/180)*(theta_deg_base-theta_deg))],
                                [np.sin((np.pi/180)*(theta_deg_base-theta_deg)),np.cos((np.pi/180)*(theta_deg_base-theta_deg))]])
    points_atlas_middle_rotated = np.matmul(rotation_matrix, points_atlas_base_middle).T
    points_atlas_middle_rotated

    #step 2.3)
    # restore original coord system
    points_atlas_rotated = np.array([points_atlas_middle_rotated[:,0]+atl_rot_base.shape[1]/2,
                                        points_atlas_middle_rotated[:,1]+atl_rot_base.shape[0]/2]).T

    #step 2.4)
    # map to coordinate system of rotated picture
    delta_x = atl_rot.shape[1]-atl_rot_base.shape[1]
    delta_y = atl_rot.shape[0]-atl_rot_base.shape[0]

    points_atlas_rotated_shifted = np.array([points_atlas_rotated[:,0]+delta_x/2,
                                        points_atlas_rotated[:,1]+delta_y/2]).T


    #step 3)
    # upscaling to extended scale; extendA does not change, hence only scaling needs to be adjusted
    offset_x = org_offset_x
    offset_y = org_offset_y
    scaling_x = (max(extentA[0], extentA[1])-offset_x)/atl_rot.shape[1]
    scaling_y = (max(extentA[2], extentA[3])-offset_y)/atl_rot.shape[0]

    points_atlas_x = points_atlas_rotated_shifted[:,0]*scaling_x+offset_x
    points_atlas_y = points_atlas_rotated_shifted[:,1]*scaling_y+offset_y

    return np.array([points_atlas_x, points_atlas_y]).T

points_atlas = ref_point_rotation(theta_deg, np.array(fixpoints[slice][:num_points]), slice, angle_fixpoint, extentA, A)

points_target = -np.roll(np.array(points_target),1,1)
points_atlas = -np.roll(points_atlas,1,1)
Li,Ti = STalign.L_T_from_points(points_atlas,points_target)
```
I hope that it can help some people
